### ISSUE TITLE
404=This page could not be found

### ISSUE THREAD

**Issue by Haxnstuff** [inertia-unblocker/inertia-client#10]
![image](https://user-images.githubusercontent.com/76791182/198313570-481ca6bb-0c18-4be7-8a03-6545a22c0f1f.png)

(Does the same thing w/ "google.com" as well)

**Comment by OnlyCS** [comment]
fixing soon -- there are problems with ultraviolet currently. please, go to proxy then select external. click the external server options button then click alloy. paste this link:
`https://alloy.backends.onlycs.net/`

note that the browser will not work

**Comment by Doomcow500** [comment]
closed issue - resolved
