### ISSUE TITLE
Might be an issue, might just be intended. 

### ISSUE THREAD

**Issue by Haxnstuff** [inertia-unblocker/inertia-client#5]
I can't tell if this is an issue or not, but I can't scroll on any part of the Inertia site, It looks like I'm supposed to see more so I'm writing this  just in case.

(This image is my entire screen btw, I'm not cutting anything out)
![image](https://user-images.githubusercontent.com/76791182/167963071-427c386e-1916-4208-b237-6fa1a264f07c.png)

**Comment by TheAlphaReturns** [comment]
fixed in 1.1.0
